owner: cyrilsebastian
repo: uptime

sites:
  - name: Public Profile
    url: https://cyrilsebastian.com
  - name: Tech Blog
    url: https://tech.cyrilsebastian.com
  - name: Personal Blog
    url: https://blog.cyrilsebastian.com
  - name: Dementia India (Prod)
    url: https://dementia.cyrilsebastian.com
  - name: Dementia India (Staging)
    url: https://dementia-staging.cyrilsebastian.in
    expectedStatusCodes:
      - 200
      - 401   
      
assignees:
  - cyrilsebastian

status-website:
  name: Cyril Sebastian — Status
  cname: status.cyrilsebastian.com
  logoUrl: https://cyrilsebastian.com/favicon.png
  navbar:
    - title: Home
      href: https://cyrilsebastian.com
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
