owner: cyrilsebastian
repo: uptime

sites:
  - name: Public Profile
    url: https://cyrilsebastian.com
  - name: Tech Blog
    url: https://tech.cyrilsebastian.com
  - name: Personal Blog
    url: https://blog.cyrilsebastian.com
  - name: Dementia India (Prod)
    url: https://dementia.cyrilsebastian.com
  - name: Dementia India (Staging)
    url: https://dementia-staging.cyrilsebastian.in
    expectedStatusCodes:
      - 200
      - 401   
      
assignees:
  - cyrilsebastian

status-website:
  name: Cyril Sebastian
  introTitle: Monitoring of Cyril's apps and sites.
  introMessage: Live status for everything public-facing.
  navbar:
    - title: Status
      href: https://status.cyrilsebastian.com
    - title: GitHub
      href: https://github.com/cyrilsebastian
    - title: Twitter
      href: https://twitter.com/cyrilsebastian

workflowSchedule:
  uptime: "*/5 * * * *"      
  responseTime: "0 23,11 * * *"
  graphs: "0 0 * * *"
  updateTemplate: "0 0 * * 0"
  summary: "0 0 * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
